# .air.toml
root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/app.exe ./cmd/invoice-extractor"
  bin = "tmp/app.exe"
  delay = 1000
  stop_on_error = true
  send_interrupt = true
  kill_delay = 500

[log]
  time = true

[color]
  main = "cyan"
  watcher = "yellow"
  build = "green"
  runner = "magenta"

[watch]
  includes = ["**/*.go"]
  excludes = [
    "tmp/**",
    "vendor/**",
    ".git/**"
  ]
