CREATE TABLE users (
	id TEXT PRIMARY KEY,
	username VARCHAR(100) UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE sessions (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	expires_at DATETIME NOT NULL,
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE jobs (
	id TEXT PRIMARY KEY,
	user_id TEXT NOT NULL,
	type VARCHAR(100) NOT NULL,
	status VARCHAR(100) NOT NULL,
	progress INTEGER NOT NULL,
	input_payload BLOB NOT NULL,
	output_payload BLOB,
	error_message TEXT,
	created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
	started_at DATETIME,
	finished_at DATETIME,
	expired_at DATETIME,
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
